In [1]:
import pandas as pd

In [2]:
df_orig = pd.read_csv("20240514-DataSheet-RUN55.csv", skiprows=20)
df_orig.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Species,Chain,Patient,Sample,UMI,RACE,Group,HEK_cells,Constant,MID
0,N701_S502,BP2338-pre-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,human,TCRb,BP2338,pre-sort,yes,no,NaN,no,no,NaN
1,N702_S502,BP2880-pre-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,human,TCRb,BP2880,pre-sort,yes,no,NaN,no,no,NaN
2,N705_S502,BP2880-CD4pTc-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,human,TCRb,BP2880,CD4+ T cells,yes,no,NaN,no,no,NaN
3,N711_S502,pSpA-004-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,human,TCRb,1123034,V4,yes,no,NaN,no,no,NaN
4,N712_S502,pSpA-010-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,human,TCRb,1123006,V4,yes,no,NaN,no,no,NaN

In [3]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Processing/$OUTDIR/Results/final/*.rr.clones_subs.csv > list-processed.txt
df_processed = pd.read_csv("list-processed.txt", header=None)
df_processed.columns = ['filename']
df_processed.head()

                                            filename
0  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
1  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
2  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
3  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
4  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...

In [4]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_processed['Sample_Name'] = [x for x in map(get_sample, df_processed['filename'])]
df_processed.head()

                                            filename   Sample_Name
0  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB3709-ST-T2
1  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4064-ST-T2
2  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4382-ST-T2
3  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4554-ST-T2
4  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4679-ST-T2

In [5]:
df = pd.merge(df_orig, df_processed, how='left', on='Sample_Name')
df

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Chain,Patient,Sample,UMI,RACE,Group,HEK_cells,Constant,MID,filename
0,N701_S502,BP2338-pre-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,TCRb,BP2338,pre-sort,yes,no,NaN,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
1,N702_S502,BP2880-pre-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,TCRb,BP2880,pre-sort,yes,no,NaN,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
2,N705_S502,BP2880-CD4pTc-T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,TCRb,BP2880,CD4+ T cells,yes,no,NaN,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
3,N711_S502,pSpA-004-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,TCRb,1123034,V4,yes,no,NaN,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
4,N712_S502,pSpA-010-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,TCRb,1123006,V4,yes,no,NaN,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,N715_S517,ID478t3-RNA-B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S173,...,BCRh,ID478,t=3,yes,no,RNA,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
173,N716_S517,ID669t0-DNA-B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S174,...,BCRh,ID669,t=0,yes,no,DNA,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
174,N718_S517,ID668t0-DNA-B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S175,...,BCRh,ID668,t=0,yes,no,DNA,no,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
175,N719_S517,BB6423-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S176,...,TCRb,BB6423,ST,yes,no,NaN,yes,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
176,N720_S517,BB6649-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S177,...,TCRb,BB6649,ST,yes,no,NaN,yes,no,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...

In [6]:
# Get list of unprocessed samples
df = df[df['filename'].isna()]
len(df)

2

In [7]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Data/NameOfDataset_1/Raw/*.fastq.gz > list-fastq.txt
df_fastq = pd.read_csv("list-fastq.txt", header=None)
df_fastq.columns = ['fastq']
df_fastq.head()

                                               fastq
0  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
1  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
2  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
3  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...
4  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...

In [8]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_fastq['Sample_Name'] = [x for x in map(get_sample, df_fastq['fastq'])]
df_fastq.head()

                                               fastq   Sample_Name
0  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB3709-ST-T2
1  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB3709-ST-T2
2  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4064-ST-T2
3  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4064-ST-T2
4  /mnt/immunogenomics/RUNS/run55-20240514-miseq/...  BB4382-ST-T2

In [9]:
# Combined list unprocessed samples with fastq paths
df = pd.merge(df, df_fastq, how='left', on='Sample_Name')
df.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Patient,Sample,UMI,RACE,Group,HEK_cells,Constant,MID,filename,fastq
0,N716_S508,Bx1578-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S86,...,Bx1578,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
1,N716_S508,Bx1578-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S86,...,Bx1578,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
2,N711_S515,Bx1338-ST-T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S143,...,Bx1338,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
3,N711_S515,Bx1338-ST-T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S143,...,Bx1338,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...

In [10]:
len(df)

4

In [11]:
# Check which reference should be used
df.groupby(['Species', 'Chain', 'UMI', 'Constant', 'RACE']).agg({'Sample_Name': 'nunique'})

                                 Sample_Name
Species Chain UMI Constant RACE
human   TCRb  yes no       no              2

In [12]:
df_human_TCRb = df[(df['Species'] == 'human') & (df['Chain'] == "TCRb")]
df_human_BCRh_UMI = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['UMI'] == "yes") & (df['RACE'] == "no")]
df_human_BCRh_RACE_noC = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['RACE'] == "yes") & (df['Constant'] == "no")]
df_human_BCRh_RACE_withC = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['RACE'] == "yes") & (df['Constant'] == "yes")]
df_mouse_BCRk = df[(df['Species'] == 'mouse') & (df['Chain'] == "BCRk")]

In [13]:
df_human_TCRb = df_human_TCRb['fastq']
df_human_BCRh_UMI = df_human_BCRh_UMI['fastq']
df_human_BCRh_RACE_noC = df_human_BCRh_RACE_noC['fastq']
df_human_BCRh_RACE_withC = df_human_BCRh_RACE_withC['fastq']
df_mouse_BCRk = df_mouse_BCRk['fastq']

In [14]:
df_human_TCRb.to_csv("SAMPLES-human-TCRb", header=False, index=False)
df_human_BCRh_UMI.to_csv("SAMPLES-human-BCRh-UMI", header=False, index=False)
df_human_BCRh_RACE_noC.to_csv("SAMPLES-human-BCRh-RACE-noC", header=False, index=False)
df_human_BCRh_RACE_withC.to_csv("SAMPLES-human-BCRh-RACE-withC", header=False, index=False)
#df_mouse_BCRk.to_csv("SAMPLES-mouse-BCRk", header=False, index=False)

In [15]:
df

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Patient,Sample,UMI,RACE,Group,HEK_cells,Constant,MID,filename,fastq
0,N716_S508,Bx1578-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S86,...,Bx1578,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
1,N716_S508,Bx1578-ST-T2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S86,...,Bx1578,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
2,N711_S515,Bx1338-ST-T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S143,...,Bx1338,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...
3,N711_S515,Bx1338-ST-T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S143,...,Bx1338,ST,yes,no,NaN,yes,no,NaN,NaN,/mnt/immunogenomics/RUNS/run55-20240514-miseq/...