In [1]:
import pandas as pd

In [2]:
df_orig = pd.read_csv("20230823-DataSheet-RUN52.csv", skiprows=20)
df_orig.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Species,Chain,Patient,Sample,UMI,Constant,MID,HEK_cells,Group,RACE
0,N701_S502,AB-RTX56-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,human,TCRb,10-01-0003,V6_M12,yes,no,NaN,no,NaN,no
1,N702_S502,AB-RTX58-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,human,TCRb,10-01-0007,V6_M12,yes,no,NaN,no,NaN,no
2,N703_S502,AB-RTX59-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,human,TCRb,10-04-0007,V6_M12,yes,no,NaN,no,NaN,no
3,N704_S502,AB-RTX60-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,human,TCRb,40-01-0014,V6_M12,yes,no,NaN,no,NaN,no
4,N705_S502,AB-RTX61-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,human,TCRb,40-01-0016,V6_M12,yes,no,NaN,no,NaN,no

In [3]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Processing/$OUTDIR/Results/final/*-clones-mut-sites.csv > list-processed.txt
df_processed = pd.read_csv("list-processed.txt", header=None)
df_processed.columns = ['filename']
df_processed.head()

                                            filename
0  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
1  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
2  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
3  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
4  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...

In [4]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_processed['Sample_Name'] = [x for x in map(get_sample, df_processed['filename'])]
df_processed.head()

                                            filename           Sample_Name
0  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...   A2-ERO-d21-blood-Bh
1  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...  A2-ESRA-d90-blood-Bh
2  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...     A2-ESRA-d90-SP-Bh
3  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...  A2-ESRO-d21-blood-Bh
4  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...  A2-VERO-d21-blood-Bh

In [5]:
df = pd.merge(df_orig, df_processed, how='left', on='Sample_Name')
df

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Chain,Patient,Sample,UMI,Constant,MID,HEK_cells,Group,RACE,filename
0,N701_S502,AB-RTX56-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,TCRb,10-01-0003,V6_M12,yes,no,NaN,no,NaN,no,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
1,N702_S502,AB-RTX58-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,TCRb,10-01-0007,V6_M12,yes,no,NaN,no,NaN,no,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
2,N703_S502,AB-RTX59-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,TCRb,10-04-0007,V6_M12,yes,no,NaN,no,NaN,no,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
3,N704_S502,AB-RTX60-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,TCRb,40-01-0014,V6_M12,yes,no,NaN,no,NaN,no,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
4,N705_S502,AB-RTX61-Tu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,TCRb,40-01-0016,V6_M12,yes,no,NaN,no,NaN,no,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,N714_S517,ID546Mem-IgA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S165,...,BCRh,ID546t0,Membrane,no,yes,NaN,no,IgA,yes,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
165,N715_S517,ID566Mem-IgM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S166,...,BCRh,ID566t0,Membrane,no,yes,NaN,no,IgM,yes,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
166,N716_S517,ID566Mem-IgD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S167,...,BCRh,ID566t0,Membrane,no,yes,NaN,no,IgD,yes,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
167,N718_S517,ID566Mem-IgA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S168,...,BCRh,ID566t0,Membrane,no,yes,NaN,no,IgA,yes,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
168,N719_S517,ID657Mem-IgM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S169,...,BCRh,ID657t0,Membrane,no,yes,NaN,no,IgM,yes,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...

In [6]:
# Get list of unprocessed samples
df = df[df['filename'].isna()]
len(df)

6

In [7]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Data/NameOfDataset_1/Raw/*.fastq.gz > list-fastq.txt
df_fastq = pd.read_csv("list-fastq.txt", header=None)
df_fastq.columns = ['fastq']
df_fastq.head()

                                               fastq
0  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
1  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
2  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
3  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...
4  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...

In [8]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_fastq['Sample_Name'] = [x for x in map(get_sample, df_fastq['fastq'])]
df_fastq.head()

                                               fastq           Sample_Name
0  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...   A1-ERO-d21-blood-Bh
1  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...   A1-ERO-d21-blood-Bh
2  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...  A1-ESRA-d90-blood-Bh
3  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...  A1-ESRA-d90-blood-Bh
4  /mnt/immunogenomics/RUNS/run52-20230823-miseq/...     A1-ESRA-d90-SP-Bh

In [9]:
# Combined list unprocessed samples with fastq paths
df = pd.merge(df, df_fastq, how='left', on='Sample_Name')
df.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Patient,Sample,UMI,Constant,MID,HEK_cells,Group,RACE,filename,fastq
0,N716_S502,A1-ESRA-d90-blood-Bh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S13,...,A1,Blood-day90,yes,no,NaN,no,ESRA,no,NaN,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
1,N716_S502,A1-ESRA-d90-blood-Bh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S13,...,A1,Blood-day90,yes,no,NaN,no,ESRA,no,NaN,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
2,N712_S503,A1-ESRA-d90-SP-Bh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S26,...,A1,SP-day90,yes,no,NaN,no,ESRA,no,NaN,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
3,N712_S503,A1-ESRA-d90-SP-Bh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S26,...,A1,SP-day90,yes,no,NaN,no,ESRA,no,NaN,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...
4,N711_S505,A1-VERO-d21-blood-Bh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S41,...,A1,Blood-day21,yes,no,NaN,no,VERO,no,NaN,/mnt/immunogenomics/RUNS/run52-20230823-miseq/...

In [10]:
len(df)

12

In [11]:
# Check which reference should be used
df.groupby(['Species', 'Chain', 'UMI', 'Constant', 'RACE']).agg({'Sample_Name': 'nunique'})

                                 Sample_Name
Species Chain UMI Constant RACE
mouse   BCRh  yes no       no              6

In [12]:
df_human_TCRb = df[(df['Species'] == 'human') & (df['Chain'] == "TCRb")]
df_human_BCRh = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh")]
df_mouse_BCRh = df[(df['Species'] == 'mouse') & (df['Chain'] == "BCRh")]

In [13]:
df_human_TCRb = df_human_TCRb['fastq']
df_human_BCRh = df_human_BCRh['fastq']
df_mouse_BCRh = df_mouse_BCRh['fastq']

In [14]:
df_human_TCRb.to_csv("SAMPLES-human-TCRb", header=False, index=False)
df_human_BCRh.to_csv("SAMPLES-human-BCRh", header=False, index=False)
df_mouse_BCRh.to_csv("SAMPLES-mouse-BCRh", header=False, index=False)