In [1]:
import pandas as pd

In [2]:
df_orig = pd.read_csv("20240227-DataSheet-RUN54.csv", skiprows=20)
df_orig.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Chain,Patient,Sample,UMI,Constant,HEK_cells,Group,MID,RACE,ChainOriginal
0,N701_S502,T2B001-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,BCRh,32,HC,yes,no,no,NaN,NaN,yes,BCRh
1,N702_S502,T2B002-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,BCRh,41,HC,yes,no,no,NaN,NaN,yes,BCRh
2,N703_S502,T2B003-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,BCRh,51,HC,yes,no,no,NaN,NaN,yes,BCRh
3,N704_S502,T2B004-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,BCRh,77,HC,yes,no,no,NaN,NaN,yes,BCRh
4,N706_S502,T2B008-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,BCRh,110,PF29,yes,no,no,NaN,NaN,yes,BCRh

In [3]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Processing/$OUTDIR/Results/final/*.rr.clones_subs.csv > list-processed.txt
df_processed = pd.read_csv("list-processed.txt", header=None)
df_processed.columns = ['filename']
df_processed.head()

                                            filename
0  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
1  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
2  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
3  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
4  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...

In [4]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_processed['Sample_Name'] = [x for x in map(get_sample, df_processed['filename'])]
df_processed.head()

                                            filename Sample_Name
0  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5072-T
1  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5404-T
2  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5463-T
3  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5466-T
4  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5702-T

In [5]:
df = pd.merge(df_orig, df_processed, how='left', on='Sample_Name')
df

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Patient,Sample,UMI,Constant,HEK_cells,Group,MID,RACE,ChainOriginal,filename
0,N701_S502,T2B001-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,32,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN
1,N702_S502,T2B002-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,41,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN
2,N703_S502,T2B003-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,51,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN
3,N704_S502,T2B004-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S4,...,77,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN
4,N706_S502,T2B008-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S5,...,110,PF29,yes,no,no,NaN,NaN,yes,BCRh,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,N724_S522,Test08-Bp3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S373,...,Test08,UMI M805+M818,yes,no,no,NaN,NaN,no,BCRh,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
373,N726_S522,Test09-Bp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S374,...,Test09,UMI M805+M818,yes,no,no,NaN,NaN,no,BCRh,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
374,N727_S522,Test09-Bp2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S375,...,Test09,UMI M805+M818,yes,no,no,NaN,NaN,no,BCRh,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
375,N728_S522,Test09-Bp3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S376,...,Test09,UMI M805+M818,yes,no,no,NaN,NaN,no,BCRh,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
376,N729_S522,Test10-Bp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S377,...,Test10,UMI M805+M818,yes,no,no,NaN,NaN,no,BCRh,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...

In [6]:
# Get list of unprocessed samples
df = df[df['filename'].isna()]
len(df)

46

In [7]:
# Preparation: ls /mnt/immunogenomics/RUNS/$RUN/Data/NameOfDataset_1/Raw/*.fastq.gz > list-fastq.txt
df_fastq = pd.read_csv("list-fastq.txt", header=None)
df_fastq.columns = ['fastq']
df_fastq.head()

                                               fastq
0  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
1  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
2  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
3  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...
4  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...

In [8]:
get_sample = lambda x: x.split("/")[-1].split('_')[0]
df_fastq['Sample_Name'] = [x for x in map(get_sample, df_fastq['fastq'])]
df_fastq.head()

                                               fastq Sample_Name
0  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5072-T
1  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5072-T
2  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5404-T
3  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5404-T
4  /mnt/immunogenomics/RUNS/run54-20240227-miseq/...    BB5463-T

In [9]:
# Combined list unprocessed samples with fastq paths
df = pd.merge(df, df_fastq, how='left', on='Sample_Name')
df.head()

,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Run,Nr,...,Sample,UMI,Constant,HEK_cells,Group,MID,RACE,ChainOriginal,filename,fastq
0,N701_S502,T2B001-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
1,N701_S502,T2B001-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S1,...,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
2,N702_S502,T2B002-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
3,N702_S502,T2B002-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S2,...,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...
4,N703_S502,T2B003-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S3,...,HC,yes,no,no,NaN,NaN,yes,BCRh,NaN,/mnt/immunogenomics/RUNS/run54-20240227-miseq/...

In [10]:
len(df)

92

In [11]:
# Check which reference should be used
df.groupby(['Species', 'Chain', 'UMI', 'Constant', 'RACE']).agg({'Sample_Name': 'nunique'})

                                 Sample_Name
Species Chain UMI Constant RACE
human   BCRh  yes no       yes            46

In [12]:
df_human_TCRb = df[(df['Species'] == 'human') & (df['Chain'] == "TCRb")]
df_human_BCRh_UMI = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['UMI'] == "yes") & (df['RACE'] == "no")]
df_human_BCRh_RACE_noC = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['RACE'] == "yes") & (df['Constant'] == "no")]
df_human_BCRh_RACE_withC = df[(df['Species'] == 'human') & (df['Chain'] == "BCRh") & (df['RACE'] == "yes") & (df['Constant'] == "yes")]
df_mouse_BCRk = df[(df['Species'] == 'mouse') & (df['Chain'] == "BCRk")]

In [13]:
df_human_TCRb = df_human_TCRb['fastq']
df_human_BCRh_UMI = df_human_BCRh_UMI['fastq']
df_human_BCRh_RACE_noC = df_human_BCRh_RACE_noC['fastq']
df_human_BCRh_RACE_withC = df_human_BCRh_RACE_withC['fastq']
df_mouse_BCRk = df_mouse_BCRk['fastq']

In [14]:
df_human_TCRb.to_csv("SAMPLES-human-TCRb", header=False, index=False)
df_human_BCRh_UMI.to_csv("SAMPLES-human-BCRh-UMI", header=False, index=False)
df_human_BCRh_RACE_noC.to_csv("SAMPLES-human-BCRh-RACE-noC", header=False, index=False)
df_human_BCRh_RACE_withC.to_csv("SAMPLES-human-BCRh-RACE-withC", header=False, index=False)
#df_mouse_BCRk.to_csv("SAMPLES-mouse-BCRk", header=False, index=False)