In [2]:
import pandas as pd
import os

## Read sample information

In [27]:
df = pd.read_excel("20160201_RUN259_MIDlijst.xls", header=1)
df.head()

,SPECIES,REGION,MID.ID,MID.SEQ,SAMPLE.ID,READS.N,PROJECT,SAMPLE,GROUP,NOTES
0,human,1,2,CTGACCTTAC,5803166 t=0,10000,IgG4,PBMC,unknown,NaN
1,human,1,3,TGACTCTTAC,3330629 t=0,10000,IgG4,PBMC,unknown,NaN
2,human,1,4,CTTGACTTAC,JBI071,4162,JBI,PBMC,unknown,rerun
3,human,1,5,TGGACCTTAC,JBI026,1827,JBI,PBMC,unknown,rerun
4,human,1,6,ACACTCTTAC,JBI075,10000,JBI,PBMC,unknown,2ndX work-up

In [33]:
region = 2
prefix = 'run259-JV3AIYM02-'

In [34]:
selection = df.loc[df['SAMPLE.ID'].str.startswith('JBI')]
selection = selection[selection['REGION'] == region]
selection.head()

,SPECIES,REGION,MID.ID,MID.SEQ,SAMPLE.ID,READS.N,PROJECT,SAMPLE,GROUP,NOTES
29,human,2,2,CTGACCTTAC,JBI148,10000,NaN,PBMC,unknown,NaN
30,human,2,3,TGACTCTTAC,JBI151,10000,NaN,PBMC,unknown,NaN
31,human,2,4,CTTGACTTAC,JBI107,3519,NaN,PBMC,unknown,rerun
32,human,2,5,TGGACCTTAC,JBI154,10000,NaN,PBMC,unknown,NaN
33,human,2,6,ACACTCTTAC,JBI156,10000,NaN,PBMC,unknown,NaN

In [35]:
d = dict()
cols = ['MID.SEQ', 'SAMPLE.ID']
for mid, sampleId in selection[cols].to_dict(orient='split')['data']:
    d[mid] = sampleId
d

{'CTGACCTTAC': 'JBI148',
 'TGACTCTTAC': 'JBI151',
 'CTTGACTTAC': 'JBI107',
 'TGGACCTTAC': 'JBI154',
 'ACACTCTTAC': 'JBI156',
 'TCGGACTTAC': 'JBI157',
 'ATAACCTTAC': 'JBI161',
 'CGTCTCTTAC': 'JBI033',
 'AGTCACTTAC': 'JBI162',
 'CCGAGCTTAC': 'JBI117',
 'TTAGTCTTAC': 'JBI164',
 'ACAGGCTTAC': 'JBI165',
 'CTTAGCTTAC': 'JBI167',
 'TGGCGCTTAC': 'JBI168',
 'AGACGCTTAC': 'JBI129',
 'ACATGACTTA': 'JBI172',
 'CTCGACCTTA': 'JBI173',
 'CTGTGACTTA': 'JBI175',
 'TGCGACCTTA': 'JBI176',
 'ACAACTCTTA': 'JBI044',
 'TCTGGACTTA': 'JBI178',
 'ATGAACCTTA': 'JBI144',
 'CGATCTCTTA': 'JBI180',
 'AGCTCACTTA': 'JBI181',
 'CCTGAGCCTT': 'JBI104',
 'TTGAGTCCTT': 'JBI179',
 'ACTAGGCCTT': 'JBI183',
 'CTGTAGCCTT': 'JBI186',
 'TGCGCGCCTT': 'JBI110',
 'TCGGACACCT': 'JBI197',
 'CGTCTACCTT': 'JBI198',
 'CACTTGACCT': 'JBI152'}

## Rename fastq files

In [36]:
myfiles = list()
for f in os.listdir('split'):
    if f.startswith(prefix) and f.endswith('.fastq.gz'):
        myfiles.append(f)
print(myfiles)

['run259-JV3AIYM02-nomatch.fastq.gz', 'run259-JV3AIYM02-TTAGTCTTAC.fastq.gz', 'run259-JV3AIYM02-TCGGACTTAC.fastq.gz', 'run259-JV3AIYM02-TTGAGTCCTT.fastq.gz', 'run259-JV3AIYM02-ATAACCTTAC.fastq.gz', 'run259-JV3AIYM02-ACAGGCTTAC.fastq.gz', 'run259-JV3AIYM02-CGTCTACCTT.fastq.gz', 'run259-JV3AIYM02-ACTAGGCCTT.fastq.gz', 'run259-JV3AIYM02-CCGAGCTTAC.fastq.gz', 'run259-JV3AIYM02-AGTCACTTAC.fastq.gz', 'run259-JV3AIYM02-CGATCTCTTA.fastq.gz', 'run259-JV3AIYM02-TGGACCTTAC.fastq.gz', 'run259-JV3AIYM02-CTTAGCTTAC.fastq.gz', 'run259-JV3AIYM02-CACTTGACCT.fastq.gz', 'run259-JV3AIYM02-ACATGACTTA.fastq.gz', 'run259-JV3AIYM02-CTGTGACTTA.fastq.gz', 'run259-JV3AIYM02-TCTGGACTTA.fastq.gz', 'run259-JV3AIYM02-AGACGCTTAC.fastq.gz', 'run259-JV3AIYM02-CTGACCTTAC.fastq.gz', 'run259-JV3AIYM02-ACACTCTTAC.fastq.gz', 'run259-JV3AIYM02-TGCGACCTTA.fastq.gz', 'run259-JV3AIYM02-CCTGAGCCTT.fastq.gz', 'run259-JV3AIYM02-CTCGACCTTA.fastq.gz', 'run259-JV3AIYM02-AGCTCACTTA.fastq.gz', 'run259-JV3AIYM02-CTGTAGCCTT.fastq.gz', 'run259-JV3AIYM02-TCGGACACCT.fastq.gz', 'run259-JV3AIYM02-TGACTCTTAC.fastq.gz', 'run259-JV3AIYM02-TGCGCGCCTT.fastq.gz', 'run259-JV3AIYM02-CTTGACTTAC.fastq.gz', 'run259-JV3AIYM02-ATGAACCTTA.fastq.gz', 'run259-JV3AIYM02-TGGCGCTTAC.fastq.gz', 'run259-JV3AIYM02-CGTCTCTTAC.fastq.gz', 'run259-JV3AIYM02-ACAACTCTTA.fastq.gz', 'run259-JV3AIYM02-TGTACTCTTA.fastq.gz', 'run259-JV3AIYM02-ACACTTACCT.fastq.gz', 'run259-JV3AIYM02-CTGACTCCTT.fastq.gz', 'run259-JV3AIYM02-AGTTCGTCCT.fastq.gz']

In [37]:
s = 1
for f in myfiles:
    mid = f.replace(prefix, '')
    mid = mid.replace('.fastq.gz', '')
    sampleId = d.get(mid, 'unknown')
    new_f = sampleId + "-" + f
    new_f = new_f.replace('.fastq.gz', '_S' + str(s) + '_L001.assembled.fastq.gz')
    print("mv", f, new_f)
    s = s + 1

mv run259-JV3AIYM02-nomatch.fastq.gz unknown-run259-JV3AIYM02-nomatch_S1_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TTAGTCTTAC.fastq.gz JBI164-run259-JV3AIYM02-TTAGTCTTAC_S2_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TCGGACTTAC.fastq.gz JBI157-run259-JV3AIYM02-TCGGACTTAC_S3_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TTGAGTCCTT.fastq.gz JBI179-run259-JV3AIYM02-TTGAGTCCTT_S4_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ATAACCTTAC.fastq.gz JBI161-run259-JV3AIYM02-ATAACCTTAC_S5_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACAGGCTTAC.fastq.gz JBI165-run259-JV3AIYM02-ACAGGCTTAC_S6_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CGTCTACCTT.fastq.gz JBI198-run259-JV3AIYM02-CGTCTACCTT_S7_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACTAGGCCTT.fastq.gz JBI183-run259-JV3AIYM02-ACTAGGCCTT_S8_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CCGAGCTTAC.fastq.gz JBI117-run259-JV3AIYM02-CCGAGCTTAC_S9_L001.assembled.fastq.gz
mv run259-JV3AIYM02-AGTCACTTAC.fastq.gz JBI162-run259-JV3AIYM02-AGTCACTTAC_S10_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CGATCTCTTA.fastq.gz JBI180-run259-JV3AIYM02-CGATCTCTTA_S11_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGGACCTTAC.fastq.gz JBI154-run259-JV3AIYM02-TGGACCTTAC_S12_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTTAGCTTAC.fastq.gz JBI167-run259-JV3AIYM02-CTTAGCTTAC_S13_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CACTTGACCT.fastq.gz JBI152-run259-JV3AIYM02-CACTTGACCT_S14_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACATGACTTA.fastq.gz JBI172-run259-JV3AIYM02-ACATGACTTA_S15_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTGTGACTTA.fastq.gz JBI175-run259-JV3AIYM02-CTGTGACTTA_S16_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TCTGGACTTA.fastq.gz JBI178-run259-JV3AIYM02-TCTGGACTTA_S17_L001.assembled.fastq.gz
mv run259-JV3AIYM02-AGACGCTTAC.fastq.gz JBI129-run259-JV3AIYM02-AGACGCTTAC_S18_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTGACCTTAC.fastq.gz JBI148-run259-JV3AIYM02-CTGACCTTAC_S19_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACACTCTTAC.fastq.gz JBI156-run259-JV3AIYM02-ACACTCTTAC_S20_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGCGACCTTA.fastq.gz JBI176-run259-JV3AIYM02-TGCGACCTTA_S21_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CCTGAGCCTT.fastq.gz JBI104-run259-JV3AIYM02-CCTGAGCCTT_S22_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTCGACCTTA.fastq.gz JBI173-run259-JV3AIYM02-CTCGACCTTA_S23_L001.assembled.fastq.gz
mv run259-JV3AIYM02-AGCTCACTTA.fastq.gz JBI181-run259-JV3AIYM02-AGCTCACTTA_S24_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTGTAGCCTT.fastq.gz JBI186-run259-JV3AIYM02-CTGTAGCCTT_S25_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TCGGACACCT.fastq.gz JBI197-run259-JV3AIYM02-TCGGACACCT_S26_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGACTCTTAC.fastq.gz JBI151-run259-JV3AIYM02-TGACTCTTAC_S27_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGCGCGCCTT.fastq.gz JBI110-run259-JV3AIYM02-TGCGCGCCTT_S28_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTTGACTTAC.fastq.gz JBI107-run259-JV3AIYM02-CTTGACTTAC_S29_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ATGAACCTTA.fastq.gz JBI144-run259-JV3AIYM02-ATGAACCTTA_S30_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGGCGCTTAC.fastq.gz JBI168-run259-JV3AIYM02-TGGCGCTTAC_S31_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CGTCTCTTAC.fastq.gz JBI033-run259-JV3AIYM02-CGTCTCTTAC_S32_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACAACTCTTA.fastq.gz JBI044-run259-JV3AIYM02-ACAACTCTTA_S33_L001.assembled.fastq.gz
mv run259-JV3AIYM02-TGTACTCTTA.fastq.gz unknown-run259-JV3AIYM02-TGTACTCTTA_S34_L001.assembled.fastq.gz
mv run259-JV3AIYM02-ACACTTACCT.fastq.gz unknown-run259-JV3AIYM02-ACACTTACCT_S35_L001.assembled.fastq.gz
mv run259-JV3AIYM02-CTGACTCCTT.fastq.gz unknown-run259-JV3AIYM02-CTGACTCCTT_S36_L001.assembled.fastq.gz
mv run259-JV3AIYM02-AGTTCGTCCT.fastq.gz unknown-run259-JV3AIYM02-AGTTCGTCCT_S37_L001.assembled.fastq.gz