In [1]:
import pandas as pd

In [2]:
clonesFile = "AMC-TC-x001-HL-clones-mut.csv"
donorFile = "seurat_coupling_mRNA_HTO_VDJ.raw.txt"

In [3]:
outFile = "AMC-TC-x001-HL-clones-mut-donors.csv"

In [4]:
df_clones = pd.read_csv(clonesFile)
df_clones.head()

,barcode,cdr3_heavy_nunique,cdr3_heavy_concat,acc_x_nunique,acc_x_concat,V_sub_x_nunique,V_sub_x_concat,J_sub_x_nunique,J_sub_x_concat,cdr3nuc_x_nunique,...,cdr3pep_y_nunique,cdr3pep_y_concat,mut.count.V.heavy_mean,mut.count.V.heavy_median,mut.count.J.heavy_mean,mut.count.J.heavy_median,mut.count.V.light_mean,mut.count.V.light_median,mut.count.J.light_mean,mut.count.J.light_median
0,AAACCTGAGGCTAGGT,1,IGH:CAKDHSSWYEWYSLAPGDYW,1,AAACCTGAGGCTAGGT-1_contig_2,1,IGHV3-23,1,IGHJ4,1,...,1,CQQYGSSPLFTFG,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,AAACCTGAGTGCGATG,1,IGH:CATHLIGSHFDYW,1,AAACCTGAGTGCGATG-1_contig_1,1,IGHV1-69,1,IGHJ4,1,...,2,CSSYTSSSTLVFG;CQQYDSYSTFG,0.000000,0.0,0.0,0.0,5.714286,2.0,0.0,0.0
2,AAACCTGGTTCAGTAC,1,IGH:CARDQAIAAADLYYFDYW,2,AAACCTGGTTCAGTAC-1_contig_1;AAACCTGGTTCAGTAC-1...,1,IGHV3-30-3,1,IGHJ4,1,...,1,CQQYYSYPPITFG,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,AAACCTGGTTCATGGT,1,IGH:CARLGVGATGVYDYW,2,AAACCTGGTTCATGGT-1_contig_2;AAACCTGGTTCATGGT-1...,1,IGHV4-59,1,IGHJ4,1,...,1,CQAWDSSNVVFG,0.333333,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,AAACCTGTCCCGACTT,1,IGH:CARDLSWGVVANPLTGHYW,2,AAACCTGTCCCGACTT-1_contig_1;AAACCTGTCCCGACTT-1...,1,IGHV3-48,1,IGHJ4,1,...,1,CQAWDSSLVFG,1.000000,1.0,0.0,0.0,0.000000,0.0,0.0,0.0

In [5]:
df_donors = pd.read_csv(donorFile, sep="\t")
df_donors.head()

,Unnamed: 0,orig.ident,nCount_RNA,nFeature_RNA,nCount_HTO,nFeature_HTO,HTO_maxID,HTO_secondID,HTO_margin,HTO_classification,HTO_classification.global,hash.ID,barcode,CTgene,CTnt,CTaa,CTstrict,Frequency,cloneType,indicator
0,AAACCTGAGTGCGATG,SeuratProject,963,410,7805,10,C0251,C0252,0.567296,C0251_C0252,Doublet,Doublet,AAACCTGAGTGCGATG,IGHV1-69D.IGHJ4.None.IGHM_IGLV2-14.IGLJ2.IGLC2,TGTGCGACACACCTCATCGGGTCACACTTTGACTACTGG_TGCAGC...,CATHLIGSHFDYW_CSSYTSSSTLVF,IGH.2_IGHV1-69D_IGLC.2_IGLV2-14,1,Single (0 < X <= 1),1
1,AAACCTGCAATCTACG,SeuratProject,2162,708,6576,7,C0259,C0252,5.687409,C0259,Singlet,C0259,AAACCTGCAATCTACG,IGHV4-59.IGHJ3.None.IGHM_IGLV3-25.IGLJ1.IGLC1,TGTGCGAGATACTTCGATGCTTTTGATATCTGG_TGTCAATCAGCA...,CARYFDAFDIW_CQSADSSGTYVF,IGH.3_IGHV4-59_IGLC.3_IGLV3-25,8,Medium (5 < X <= 20),1
2,AAACCTGGTTCAGTAC,SeuratProject,2722,784,6527,8,C0259,C0253,5.565782,C0259,Singlet,C0259,AAACCTGGTTCAGTAC,IGHV3-33.IGHJ4.None.IGHM_IGKV1-8.IGKJ3.IGKC,TGTGCGAGAGACCAAGCTATAGCAGCAGCCGACCTTTACTACTTTG...,CARDQAIAAADLYYFDYW_CQQYYSYPPITF,IGH.4_IGHV3-33_IGLC.4_IGKV1-8,2,Small (1 < X <= 5),1
3,AAACCTGGTTCATGGT,SeuratProject,2196,670,3309,8,C0254,C0252,4.811885,C0254,Singlet,C0254,AAACCTGGTTCATGGT,IGHV4-59.IGHJ4.None.IGHM_IGLV3-1.IGLJ2.IGLC2,TGTGCGAGACTGGGGGTGGGAGCTACCGGAGTTTATGACTACTGG_...,CARLGVGATGVYDYW_CQAWDSSNVVF,IGH.5_IGHV4-59_IGLC.5_IGLV3-1,2,Small (1 < X <= 5),1
4,AAACCTGTCCCGACTT,SeuratProject,8598,1936,6450,10,C0259,C0257,5.215316,C0257_C0259,Doublet,Doublet,AAACCTGTCCCGACTT,IGHV3-48.IGHJ4.None.IGHM_IGLV3-1.IGLJ2.IGLC2,TGTGCGAGAGATCTTAGTTGGGGGGTGGTAGCTAATCCATTAACGG...,CARDLSWGVVANPLTGHYW_CQAWDSSLVF,IGH.6_IGHV3-48_IGLC.6_IGLV3-1,1,Single (0 < X <= 1),1

In [6]:
df = pd.merge(df_clones, df_donors, how="inner", on="barcode")
df.head()

,barcode,cdr3_heavy_nunique,cdr3_heavy_concat,acc_x_nunique,acc_x_concat,V_sub_x_nunique,V_sub_x_concat,J_sub_x_nunique,J_sub_x_concat,cdr3nuc_x_nunique,...,HTO_classification,HTO_classification.global,hash.ID,CTgene,CTnt,CTaa,CTstrict,Frequency,cloneType,indicator
0,AAACCTGAGTGCGATG,1,IGH:CATHLIGSHFDYW,1,AAACCTGAGTGCGATG-1_contig_1,1,IGHV1-69,1,IGHJ4,1,...,C0251_C0252,Doublet,Doublet,IGHV1-69D.IGHJ4.None.IGHM_IGLV2-14.IGLJ2.IGLC2,TGTGCGACACACCTCATCGGGTCACACTTTGACTACTGG_TGCAGC...,CATHLIGSHFDYW_CSSYTSSSTLVF,IGH.2_IGHV1-69D_IGLC.2_IGLV2-14,1,Single (0 < X <= 1),1
1,AAACCTGGTTCAGTAC,1,IGH:CARDQAIAAADLYYFDYW,2,AAACCTGGTTCAGTAC-1_contig_1;AAACCTGGTTCAGTAC-1...,1,IGHV3-30-3,1,IGHJ4,1,...,C0259,Singlet,C0259,IGHV3-33.IGHJ4.None.IGHM_IGKV1-8.IGKJ3.IGKC,TGTGCGAGAGACCAAGCTATAGCAGCAGCCGACCTTTACTACTTTG...,CARDQAIAAADLYYFDYW_CQQYYSYPPITF,IGH.4_IGHV3-33_IGLC.4_IGKV1-8,2,Small (1 < X <= 5),1
2,AAACCTGGTTCATGGT,1,IGH:CARLGVGATGVYDYW,2,AAACCTGGTTCATGGT-1_contig_2;AAACCTGGTTCATGGT-1...,1,IGHV4-59,1,IGHJ4,1,...,C0254,Singlet,C0254,IGHV4-59.IGHJ4.None.IGHM_IGLV3-1.IGLJ2.IGLC2,TGTGCGAGACTGGGGGTGGGAGCTACCGGAGTTTATGACTACTGG_...,CARLGVGATGVYDYW_CQAWDSSNVVF,IGH.5_IGHV4-59_IGLC.5_IGLV3-1,2,Small (1 < X <= 5),1
3,AAACCTGTCCCGACTT,1,IGH:CARDLSWGVVANPLTGHYW,2,AAACCTGTCCCGACTT-1_contig_1;AAACCTGTCCCGACTT-1...,1,IGHV3-48,1,IGHJ4,1,...,C0257_C0259,Doublet,Doublet,IGHV3-48.IGHJ4.None.IGHM_IGLV3-1.IGLJ2.IGLC2,TGTGCGAGAGATCTTAGTTGGGGGGTGGTAGCTAATCCATTAACGG...,CARDLSWGVVANPLTGHYW_CQAWDSSLVF,IGH.6_IGHV3-48_IGLC.6_IGLV3-1,1,Single (0 < X <= 1),1
4,AAACGGGAGTGTCTCA,1,IGH:CATVRITMVRGVIIYDRTFDYW,2,AAACGGGAGTGTCTCA-1_contig_2;AAACGGGAGTGTCTCA-1...,1,IGHV1-24,1,IGHJ4,1,...,C0254,Singlet,C0254,IGHV1-24.IGHJ4.IGHD3-10.IGHM_NA,TGTGCAACAGTGCGTATTACTATGGTTCGGGGAGTTATTATCTACG...,CATVRITMVRGVIIYDRTFDYW_CQQSYSTPPTF,IGH.9_IGHV1-24_IGLC.9_IGKV1D-39,1,Single (0 < X <= 1),1

In [7]:
df.to_csv(outFile)
print("Wrote", outFile, "to disk")

Wrote AMC-TC-x001-HL-clones-mut-donors.csv to disk

## Check what the overlap is

In [8]:
barcodes_clones = set(df_clones["barcode"])
barcodes_donors = set(df_donors["barcode"])

In [9]:
print("barcodes in clones:", len(barcodes_clones))
print("barcodes in donors:", len(barcodes_donors))
print("clones diff donors:", len(barcodes_clones.difference(barcodes_donors)))
print("donors diff clones:", len(barcodes_donors.difference(barcodes_clones)))
print("donors intersection clones:", len(barcodes_donors.intersection(barcodes_clones)))
print("donors union clones:", len(barcodes_donors.union(barcodes_clones)))

barcodes in clones: 2852
barcodes in donors: 3215
clones diff donors: 475
donors diff clones: 838
donors intersection clones: 2377
donors union clones: 3690

## Is number of chains consistent with the singlet/doublet annotation?

In [10]:
df_clones_single_chains = df[(df["cdr3_heavy_nunique"] == 1) & (df["cdr3_light_nunique"] == 1)]
df_clones_single_chains.groupby("HTO_classification.global").agg({'barcode': "count"})

                           barcode
HTO_classification.global
Doublet                        409
Negative                         1
Singlet                       1593

In [11]:
df_clones_multiple_chains = df[(df["cdr3_heavy_nunique"] > 1) | (df["cdr3_light_nunique"] > 1)]
df_clones_multiple_chains.groupby("HTO_classification.global").agg({'barcode': "count"})

                           barcode
HTO_classification.global
Doublet                        281
Singlet                         93